import unittest
from hanoiGame import HanoiGame
from tower import Tower

class TestHanoiGameMoves(unittest.TestCase):

  def test_action(self):
      hg = HanoiGame(None)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 3)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 4)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 3)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 5)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 3)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 4)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 3)
      hg.move()
      self.assertEqual(hg.central_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 2)
      hg.move()
      self.assertEqual(hg.left_tower.top(), 1)
      hg.move()
      self.assertEqual(hg.right_tower.top(), 6)

if __name__ == '__main__':
    unittest.main()
